### PR TITLE
Multiple updates

### PR DESCRIPTION
**Pull request by gquerret**
Multiple changes in this PR:
* Various dependency upgrade (in order to stay up to date and prepare the LS integration)
* Jenkins configuration + Docker images - Can only be executed in Riverside environment, but easily updated for any other env.
* Commit c27bcd0 introduces a breaking change: OE installations can be configured per machine (ie shared between VSC workspaces). Then the .openedge.json just has to reference the right version number. Also allows multiple projects in a single workspace, each one associated to a different OE runtime.

Is there a way a sandbox environment where plugins can be pushed only to people who want to test the new version ? I'm not confident that it won't break anything.

### CODE REVIEW

**Comment by chriscamicas** [comment]
There is currently no preview channel for this extension
And vscode marketplace does not support such feature --> https://github.com/microsoft/vscode/issues/15756
If needed we can package this extension manually and distribute the vsix file
Another way is to publish a second "Beta" or "Preview" extension

**Comment by chriscamicas** [comment]
Would you mind updating the README accordingly as well ?
Especially to mention the breaking change and the way to migrate the configuration.
Thanks

**Comment by gquerret** [comment]
Updated the README file, but the migration step can be included in the release notes of this version (switch from dlc attribute to OpenEdgeVersion).

**Comment by chriscamicas** [comment]
> 

Thnk you
Sure it could, but the README is currently the only page available in VScode when you view/manage this extension

**Pull request closed without merging**
