### PR TITLE
add autocomplete for tables, fields, methods

### PR DESCRIPTION
**Pull request by RobinHerbots**
Hi @chriscamicas ,  @ezequielgandolfi,

I was trying out some abl extensions for vscode.
What I saw where seperate efforts which are all based on each others.  The one has things straight, which another lacks, and vice-versa.

What I especially liked about your plugin @chriscamicas  was the run and debug implementation.  On the plugin from @ezequielgandolfi i liked the autocomplete for database tables and implementation of the different providers for vscode.  

So I decided to merge the features.  A first result can be seen in this PR.  
I added all the providers and database table/field support from openedge-zext.  Also hovering etc gives info.

I hope you like it and merge it.  Otherwise I create a separate fork and invite all to collaborate on this.

### CODE REVIEW

**Comment by RobinHerbots** [comment]
@chriscamicas , 

The errors you see are linter errors, ... I disabled them temporarely, ... these still need to be resolved or relaxed ;-)

**Comment by chriscamicas** [comment]
Hey, welcome onboard !
Thank you very much for your contribution.
I'd be happy to merge your modifications, but I'd rather have the lint error fixed before.
Do you mind fixing them ?
Thanks again

**Comment by RobinHerbots** [comment]
@chriscamicas , 

;-) Thank you!

No problem I will fix the linting errors and update the PR.

How about the implementation of the LSP?  Is this going somewhere?

**Comment by RobinHerbots** [comment]
Hi @chriscamicas , 

I fixed  the tslint errors, ... 
I see that tslint is deprecated and will be phased out.  Maybe switch to eslint as recommended?

**Comment by chriscamicas** [comment]
There is no WIP for an LSP implementation
However I'm convinced it's the right solution. If you are willing to explore this path, you have my full support.

**Comment by chriscamicas** [comment]
> I fixed the tslint errors, ...
Thanks

> I see that tslint is deprecated and will be phased out. Maybe switch to eslint as recommended?
Great idea, here is a new issue to track that #55

**Comment by mimorocks** [comment]
isn't this ready to be merged?

**Comment by chriscamicas** [comment]
It is ready to be merged, I just need some time to rebuild my setup and publish the extension.
Sorry for that.
BTW if someone's interested in becoming a contributor I'm looking for valuable members to help me maintain this extension as I have less time available.

**Pull request merged**
